[package]
name = "dummy_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dummy = { path = "../dummy" }
dummy_derive = { path = "../dummy_derive" }
rand = "0.8.5"
